### ISSUE TITLE
 Allow setting a SBT repositories via an env var

### ISSUE THREAD

**Issue by samj1912** [paketo-buildpacks/sbt#167]
## Describe the Enhancement

There are often times when the user/operator/stack provider would want an easy way to specify the sbt repositories to a file path in the builder/workspace which doesn't contain any credentials. For eg. changing the maven.ivy repositories.

Currently SBT BP doesn't expose a non project specific way of doing this.

## Possible Solution

Allow defining a path to sbt repositories file.

## Motivation

Support enterprise SBT repositories.

**Comment by dmikusa-pivotal** [comment]
Resolved by #168
